services:
  server-1:
    build:
      context: .
    environment:
      PROD: "true"
      ETCD_URL: etcd:2379
    restart: always
    depends_on:
      - etcd
    networks:
      - net1

  server-2:
    build:
      context: .
    environment:
      NODE_ENV: "true"
      ETCD_URL: etcd:2379
    restart: always
    depends_on:
      - etcd
    networks:
      - net1

  server-3:
    build:
      context: .
    environment:
      NODE_ENV: "true"
      ETCD_URL: etcd:2379
    restart: always
    depends_on:
      - etcd
    networks:
      - net1

  balancer:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - server-1
      - server-2
      - server-3
    networks:
      - net1

  etcd:
    image: quay.io/coreos/etcd:v3.5.1
    container_name: etcd

    command: >
      etcd
      --name etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster
      --initial-cluster-state new
      --log-level debug
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data
    restart: always
    networks:
      net1:
        aliases:
          - etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"

volumes:
  etcd-data:

networks:
  net1:
    driver: bridge
