version: '4'
services:
  server-1:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: always

  server-2:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: always

  server-3:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: always
    
  balancer:
    build: ./nginx
    ports:
      - 80:80


# docker-compose up -d --build