name: Tests
run-name: ${{ github.actor }}
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run dev
        run: npm run dev &
  run_docker:
    runs-on: ubuntu-latest

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            balancer-1
            server-1-1
            server-2-1
            server-3-1
